version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - nextcloud

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nc_user
      MYSQL_PASSWORD: nc_pass
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_PASSWORD: nc_pass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nc_user
      MYSQL_HOST: mysql

volumes:
  db_data:
